### ISSUE TITLE
没有抓取到content

### ISSUE THREAD

**Issue by xzzlhjdn** [Neo-Luo/scrapy_baidu#1]
大神，我用的python3.7，把你部分代码改了改，也改成了抓取单个关键词，具体页面解析的部分没有改，其他东西都抓到了，最后没有抓取到content，不知道什么原因。

![TIM截图20190309155817](https://user-images.githubusercontent.com/35843297/54068192-e5cc5280-4284-11e9-9dfa-bde3d1df069d.png)

![TIM截图20190309160542](https://user-images.githubusercontent.com/35843297/54068215-40fe4500-4285-11e9-8a06-c58d3851c328.png)

**Comment by Neo-Luo** [comment]
应该是python版本造成的问题。看你terminal不是都报错了吗：

> name 'unicodes' is not defined

估计是`ret = api.article(url=detail_url, fields=['text', 'next'])`这行代码报的错，可能urllib在python3有些方法变了。
你可以把代码里的try，except先去掉，看报的错具体在哪行代码（估计源头是url2io.py那边，修改成相应的python3版本函数即可）。

**Comment by Neo-Luo** [comment]
> 大神，我用的python3.7，把你部分代码改了改，也改成了抓取单个关键词，具体页面解析的部分没有改，其他东西都抓到了，最后没有抓取到content，不知道什么原因。
> 
> ![TIM截图20190309155817](https://user-images.githubusercontent.com/35843297/54068192-e5cc5280-4284-11e9-9dfa-bde3d1df069d.png)
> 
> ![TIM截图20190309160542](https://user-images.githubusercontent.com/35843297/54068215-40fe4500-4285-11e9-8a06-c58d3851c328.png)

应该是python版本造成的问题。看你terminal不是都报错了吗：

> name 'unicode' is not defined

估计是`ret = api.article(url=detail_url, fields=['text', 'next'])`这行代码报的错，可能urllib在python3有些方法变了。
你可以把代码里的try，except先去掉，看报的错具体在哪行代码（估计源头是url2io.py那边，修改成相应的python3版本函数即可）。

**Comment by xzzlhjdn** [comment]
> > 大神，我用的python3.7，把你部分代码改了改，也改成了抓取单个关键词，具体页面解析的部分没有改，其他东西都抓到了，最后没有抓取到content，不知道什么原因。
> > ![TIM截图20190309155817](https://user-images.githubusercontent.com/35843297/54068192-e5cc5280-4284-11e9-9dfa-bde3d1df069d.png)
> > ![TIM截图20190309160542](https://user-images.githubusercontent.com/35843297/54068215-40fe4500-4285-11e9-8a06-c58d3851c328.png)
> 
> 应该是python版本造成的问题。看你terminal不是都报错了吗：
> 
> > name 'unicode' is not defined
> 
> 估计是`ret = api.article(url=detail_url, fields=['text', 'next'])`这行代码报的错，可能urllib在python3有些方法变了。
> 你可以把代码里的try，except先去掉，看报的错具体在哪行代码（估计源头是url2io.py那边，修改成相应的python3版本函数即可）。

我试试用python2
