### ISSUE TITLE
您好，我直接运行后是这样的结果，我不知道哪里出错了，希望您指点一番。

### ISSUE THREAD

**Issue by L1uX1nZz** [Neo-Luo/scrapy_baidu#2]
![image](https://user-images.githubusercontent.com/44453168/54084511-83e71800-436c-11e9-8cf7-fd676fffefc9.png)

**Comment by Neo-Luo** [comment]
之前代码是在linux跑的。我更新了一下代码，以适应windows，在我这windows也能跑通。你可以下载后再试试，如果还报错error，可以把中间变量print出来看看哪一步出错了~

**Comment by L1uX1nZz** [comment]
您好，在您的帮助下没有error了，但是allNews变量里面什么都没有传入，请问这是怎么一回事。

![bug1](https://user-images.githubusercontent.com/44453168/54085580-a7b15a80-437a-11e9-9f3d-37f00f2c94af.PNG)

**Comment by L1uX1nZz** [comment]
![bug2](https://user-images.githubusercontent.com/44453168/54085594-c152a200-437a-11e9-80a9-d6f2f23e3f19.PNG)

**Comment by L1uX1nZz** [comment]
这是上面print的结果截图
![bug2](https://user-images.githubusercontent.com/44453168/54085618-f0691380-437a-11e9-91e3-37980c894a9e.PNG)

**Comment by L1uX1nZz** [comment]
![bug2](https://user-images.githubusercontent.com/44453168/54085688-99b00980-437b-11e9-8ea4-f58f65c67ea1.PNG)

**Comment by L1uX1nZz** [comment]
![bug2](https://user-images.githubusercontent.com/44453168/54085688-99b00980-437b-11e9-8ea4-f58f65c67ea1.PNG)

**Comment by Neo-Luo** [comment]
一般网站的搜索结果网页结构不会长期动态不变~你看看是不是div属性变了
![image](https://user-images.githubusercontent.com/15496620/54085730-fe6b6400-437b-11e9-94b5-7e183b8da518.png)

改成`allNews = soup.select("div.result.c-container")`

**Comment by L1uX1nZz** [comment]
谢谢您😊，已经解决了！
